name: lambda_auto_deploy

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/${{ vars.AWS_ROLE_NAME }}
          aws-region: ap-northeast-1

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: get s3 deployed file
        run: |
          aws s3 mv s3://${{ vars.S3_BUCKET }}/deployed/${{ vars.ENV }}.json .chalice/deployed/

      - name: Deploy Lambda
        run: |
          # pip install -r requirements.txt
          # chalice deploy --stage ${{ vars.ENV }}
          ls -ltr .chalice/deployed/
          cat .chalice/deployed/${{ vars.ENV }}.json
